hardware_configurations:
  - name: zen-master
    gcp_disk_size: 10
    gcp_image: projects/centos-cloud/global/images/centos-7-v20190515
    gcp_machine_type: n1-standard-4
    number_of_instances: 1
